export const colors = {
    // BACKGROUND_PRIMARY: "#FDE8E9",
    // ELEMENTS_PRIMARY: "#ADC698",
    // ELEMENTS_SECONDARY: "#343434"
    BACKGROUND_PRIMARY: "white",
    ELEMENTS_PRIMARY: "#C3D8EC",
    ELEMENTS_SECONDARY: "black"
}